name: attendance_app
description: A new Flutter project to manage student attendance with QR codes.

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2

flutter:
  uses-material-design: true
